### ISSUE TITLE
How to use weather-node with Home assistant and ESPHome

### ISSUE THREAD

**Issue by KinDR007** [AlexIII/weather-node#8]
Hi ,
its possible use node with Home assistant and ESPHome (esp32) ?
<img width="938" alt="Snímek obrazovky 2021-07-25 v 0 35 58" src="https://user-images.githubusercontent.com/61905170/126882531-2a66de38-f4d3-44a7-a561-8dc29ab58040.png">

how to get data for use in home assistant?

**Comment by AlexIII** [comment]
Hi!
There's a line `[ble_adv:053] 0x53A9: (length 6)` in the log on your picture. That's where's the data is stored. You need a way to read and manually convert those 6 bytes to temperature (fist 2 bytes), humidity (2 bytes) and status (1 byte) according to [this tabe](https://github.com/AlexIII/weather-node#ble-protocol-details). You can use `0x53A9` to distinguish this device from any other.

**Comment by KinDR007** [comment]
hi , thx for quick reaction

here its my code for ESPHome 

` on_ble_manufacturer_data_advertise:
    - mac_address: DE:AD:BE:EF:00:01
      manufacturer_id: 53A9
      then:
        - lambda: |-
            ESP_LOGD("BLE", "received manuf data: %s", hexencode(x).c_str());
            id(humidity).publish_state((x[0] << 8) + x[1]);
            id(temp).publish_state(((x[2] << 8) + x[3]) / 10.0);
            id(battble).publish_state(((x[4] << 8) ) );
            if (x[0] != 0x7b || x[1] != 0x61) return;
            int value = x[2] + (x[3] << 8);
            id(ble_sensor).publish_state(value);      


sensor:
  - platform: template
    name: "BLE Sensor temp"
    id: temp
    unit_of_measurement: "C"
    accuracy_decimals: 1

  - platform: template
    name: "BLE Sensor humidity"
    id: humidity
    unit_of_measurement: "%"
    accuracy_decimals: 0
    
  - platform: template
    id: battble  
    
  - platform: template
    name: "BLE Sensor bat"
    id: batt    
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      int batperc;
      const int battlvl = id(battble).state;
      if (battlvl == 0)
      {
          batperc = 100;
      }
      else if (battlvl == 1)
      {
          batperc = 75;
      }
      else if (battlvl == 2)
      {
          batperc = 50;
      }
      else if (battlvl == 3)
      {
          batperc = 25;
      }
      return batperc;
    `


I still have a question, what happens when the temperature value is negative?

**Comment by AlexIII** [comment]
Seems good to me. To support negative temperature you can do something like this
```
id(temp).publish_state( (x[2] & 0x80? -1 : 1) * (((x[2] & 0x7F) << 8) + x[3]) / 10.0);
```
The sign is the higher bit of x[2].
I also suggest you add 2-bit mask to read battery level
```
const int battlvl = id(battble).state & 0x03;
```

Do you mind telling what version you're using, nRF24LE1-based or Arduino-based?

**Comment by KinDR007** [comment]
Hi ,
I use Arduino pro mini board (mod. to 1.8volt@1Mhz) and nrf24l01
